### ISSUE TITLE
Very slow compared to ls

### ISSUE THREAD

**Issue by secrettriangle** [supercrabtree/k#28]

**Comment by supercrabtree** [comment]
os? setup? screen grabs?

**Comment by Alessandro-Barbieri** [comment]
Do you still need the screen grab?

**Comment by supercrabtree** [comment]
yes please

**Comment by Alessandro-Barbieri** [comment]
I'm using Debian Jessie, zsh, prezto and some other stuff for zsh

```
uname -a
Linux Host-001 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

```
```
python --version                                                      
Python 2.7.9
```
```
zsh --version 
zsh 5.0.7 (x86_64-pc-linux-gnu)
```
```
git --version 
git version 2.1.4
```


![term](https://cloud.githubusercontent.com/assets/10689739/7358876/25936796-ed39-11e4-8be1-a6ac6eb2c7a5.gif)

**Comment by zirrostig** [comment]
The slow down is due to k trying to get git status for every file and
directory, you can do k --no-vcs to disable git status checking (#37). I
expect the slow down will be much improved, once #31 is resolved.

k will probably never be as fast as ls due to the extra processing and
information it is doing and gathering.

**Comment by Alessandro-Barbieri** [comment]
I aliased k as in #37 and now is reasonably fast.
