### ISSUE TITLE
size of directories

### ISSUE THREAD

**Issue by excalibur1234** [supercrabtree/k#80]
k shows the size of directories to be 4.1k
while this is technically correct, it is a little confusing. i would prefer to not see any size of directories (e.g. display a - symbol instead).

**Comment by Mange** [comment]
It's still useful as the number of files in a directory affects its size.
I've seen directories that took megabytes in size because they had
thousands of files in them.
It was hard to open such a directory and having tools that displayed the
directory size helped me to find the issues without having to open the
directories and count filew (which would take minutes).

**Comment by excalibur1234** [comment]
i see your point.

but in this case, i would suggest using a separate color palette for directories: use black/grey/white colors (like the color palette for dates)
make all sizes of 4.1k almost invisible and directories >100k (please adjust this number as you see fit) very clearly visible.

**Comment by Mange** [comment]
That sounds useful!

**Comment by excalibur1234** [comment]
i just tested this fork: https://github.com/teancom/k

it has dynamic colors of sizes and ages of directories/files. this can help to improve the situation a little - but not solve it.

**Comment by excalibur1234** [comment]
it looks like exa is currently implementing many features of k:
https://github.com/ogham/exa

if exa's development speed stays the same, i am pretty sure that it will be an all-around better alternative to k pretty soon.

**Comment by supercrabtree** [comment]
PRs welcome
